server:
  port: 8080
  servlet:
    application-display-name: reasa

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/avada_sl_j1
    username: avada_sl_j1
    password: PSagTbAFNW
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
    database: postgresql
    database-platform: postgresql
    hibernate:
      ddl-auto: update
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER # for swagger

app:
  jwt:
    accessToken:
      secret: 1veryBigSecretKeyForReasa2veryBigSecretKeyForReasa3veryBigSecretKeyForReasa
      expired: 86400000 #1 day
    refreshToken:
      expired: 604800000 #7 days

# logging
logging:
  file:
    name: logs/avada_sl_j1-reasa-app.log
  level:
    root: info
    org:
      hibernate: info
      springframework: info
  logback:
    rollingpolicy:
      max-file-size: 10MB

